### PR TITLE
Added Assignment 3 solutions

### PR DESCRIPTION
**Pull request by MK-09-coder**

### CODE REVIEW

**Comment by MK-09-coder** [comment]
A3_Q1 output
A3_Q2 output
A3_Q3 output
A3_Q4 output
Here are the ouptuts

**Review by Cyberkid2311 — COMMENTED** [review]
@MK-09-coder Could you make your own folder for your solutions and push for PR over there?

**Comment by MK-09-coder** [comment]
Added the folder

**Comment by RoyalEagle73** [comment]
Approving but you can improve your time complexity of codes further. Also, next time please addd screenshots with more context in description. 

But Kudos, you improved a lot from your last PRs.

**Review by RoyalEagle73 — APPROVED** [review]

**Comment by MK-09-coder** [comment]
That is what hacktober fest is all about, to improve myself. Thank you very much for the opportunity given to me to improve myself.

**Pull request merged**
