### PR TITLE
Royaleagle73: Added assignment-2 solutions in clojure

### PR DESCRIPTION
**Pull request by RoyalEagle73**
**Language:** Clojure

**Evidences:**

Q1:
image

Q2:
image

Q3:
image

Q4:
image

### CODE REVIEW

**Comment by RoyalEagle73** [comment]
@Cyberkid2311  Can you please review this one. 

PS: This shows older commits also, but that has been merged as part of #1 .

**Comment by Cyberkid2311** [comment]
@RoyalEagle73 Can you run your code of prime factorization for prime numbers namely 2,3,5 and share the evidence here?

**Comment by RoyalEagle73** [comment]
> @RoyalEagle73 Can you run your code of prime factorization for prime numbers namely 2,3,5 and share the evidence here?

Updated code for edge cases in [f2ec34e](https://github.com/RoyalEagle73/Hacktoberfest-2022/pull/3/commits/f2ec34e2cb47b5bab969458dac9cb75a40115d10).

Evidences:
image

**Review by Cyberkid2311 — APPROVED** [review]
@RoyalEagle73 PR Approved

**Pull request merged**
